### ISSUE TITLE
The new script does not count correctly

### ISSUE THREAD

**Issue by Mezantrop74** [iceland2k14/bsgs#10]
Hello. The latest version of the script does the wrong calculation.
![Сохраненное изображение 2021-3-17_14-27-6 260](https://user-images.githubusercontent.com/42014520/111454940-a74cb680-872e-11eb-92c9-902e08429b88.jpg)

**Comment by Mezantrop74** [comment]
In this case, the public key is calculated correctly.
![photo_2021-03-17_14-57-30](https://user-images.githubusercontent.com/42014520/111457892-3909f300-8732-11eb-83f8-8cffa0731c1d.jpg)

**Comment by vanrzuf** [comment]
The same error is in previous version. Script is searching for matching X of pubkey. There are 2 pubkeys with the same X. 
For example:
```
priv
0000000000000000000000000000000000000000000000000000000000000002
fffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd036413f

pub
02c6047f9441ed7d6d3045406e95c07cd85c778e4b8cef3ca7abac09b95c709ee5
03c6047f9441ed7d6d3045406e95c07cd85c778e4b8cef3ca7abac09b95c709ee5
```
2priv is max_priv_key - 2

As i can see, for some reason, if we search for 2priv in range of 1priv, script gives us 1priv +2 instead max_priv_key - 1priv

**Comment by iceland2k14** [comment]
Yes it is known and expected. As we match xPoint of a Pubkey then both the Privatekey is known instantly. (PVK, Order-PVK)
Maybe i will add a strict check to display only the required PVK, next time. Thanks for pointing this.

**Comment by iceland2k14** [comment]
Order = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141

Pubkey = 02deaef545ae247123354d3db69310167704a46236775e725c690c00b1d6c8f34c, PrivateKey = 0xc7d5b70
Pubkey = 03deaef545ae247123354d3db69310167704a46236775e725c690c00b1d6c8f34c, PrivateKey = Order - 0xc7d5b70 = 0xfffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cc3b8e5d1

**Case (1) :** 
`python bsgs_v5_gmp.py -p 02deaef545ae247123354d3db69310167704a46236775e725c690c00b1d6c8f34c -b FULLbpfile.bin -bl Bigbloomfilter.bin -n 20000000000000 -keyspace 1:FFFFFFFFFFFF`

**Case (2) :**
`python bsgs_v5_gmp.py -p 03deaef545ae247123354d3db69310167704a46236775e725c690c00b1d6c8f34c -b FULLbpfile.bin -bl Bigbloomfilter.bin -n 20000000000000 -keyspace fffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cc0000000:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141`

**Comment by iceland2k14** [comment]
@Mezantrop74   Thank you Very much for this test.
I found that Yes it was a Bug related to Boundary Key. Incremental subtraction was able to match both side of boundary and caught the Wrong side key. I have added the strict check and now it will match both (x & y) before final print.
Code Updated.
