### ISSUE TITLE
RIPEMD160 Search

### ISSUE THREAD

**Issue by sezginyildirim91** [iceland2k14/bsgs#13]
Hello, great job.

I am very new to the Python language. I wanted to change the search to RIPEMD160. Since I could not solve the system, I tried to save -n size searches to .txt file. I know it's so stupid :)

I want it to search RIPEMD160 instead of public key. Can you guide me?

Also, will the RIPEMD160 search speed be similar to the current one?

Thanks.

```
while True:
    found = bsgs_keys(Q, k1, k2)
    if found == True:
        print("BSGS FOUND PrivateKey   ")
        el = time.time() - st
        break
    
    else:
        curr = time.time() - st
        el += curr
        lastitem = k2
        k1 = randk(a, b)
        print('PVK not found. {0} scanned in {1:.2f} sec. New range [+] k1: {2}'.format(scan_str(seq), curr, hex(k1)))
        st = time.time()
        k2 = k1 + seq
        k1G = ec.Scalar_Multiplication(k1, G)

# >>>>>>>>>>>>>>>>>>>>EDITING<<<<<<<<<<<<<<<<<<<<<<

        # ripemd160
        pubkey = str(ec.Point_to_Pubkey(k1G))
        def hash160(hex_str):
            sha = hashlib.sha256()
            rip = hashlib.new('ripemd160')
            sha.update(hex_str)
            rip.update(sha.digest())
            return rip.hexdigest()
        hex_str = bytearray.fromhex(pubkey)
        key_hash = hash160(hex_str)
        with open ("ripemd160.txt", "a") as i:
            i.write(pubkey + '---->' + key_hash + '\n')

# >>>>>>>>>>>>>>>>>>>>EDITING<<<<<<<<<<<<<<<<<<<<<<

print("Time Spent : {0:.5f} seconds".format(el))
```

**Comment by iceland2k14** [comment]
No. This one is specifically bsgs algo to search Pubkey.
For RIPEMD160 searching you can use these tools

- [keyhunt mode rm160](https://github.com/albertobsd/keyhunt) if on Linux with CPU
- [AltCrack](https://github.com/iceland2k14/AltCrack) for either Windows or Linux (either CPU or GPU)
- [Dormant5](https://github.com/iceland2k14/Dormant5) for using Python only with multiCPU

**Comment by nubeegimelda** [comment]
I'm trying too search ripemd160 with hex_line,can i do that?
