### ISSUE TITLE
Using only X for searching

### ISSUE THREAD

**Issue by Mezantrop74** [iceland2k14/bsgs#14]
Hello.
Why don't you use only the X coordinate for the search to save calculation time?

**Comment by Mezantrop74** [comment]
For example, I'm looking like this.
`# -*- coding: utf-8 -*-

import os
import multiprocessing
from multiprocessing import Pool
import random
import bit
from binascii import hexlify
from tqdm import tqdm

start = 0x8000000000000000
end = 0x8fffffffffffffff
p = 0
r = 0
pbar = tqdm(initial = p)


with open ("pubkey.txt","r") as all_keys:
     for line in all_keys:
          list = all_keys.read().split()

list = set(list)

while True:
     kr = random.randrange(start, end)
     priv = bit.Key.from_int(kr)
     pubk = hexlify(priv.public_key).decode()[2:]
     if pubk in list:
          print ("Hex: ",hex(kr))
          f=open("WIN.txt","a")
          f.write(hex(kr) + "\n")
          f.close
     pbar.update(1)
`

**Comment by iceland2k14** [comment]
It is already using the X for searching. All X are inside the bPfile and they are filled in bloom for quick search.
Y is checked only for the Final Found Key before printing it.
