### ISSUE TITLE
Thread or Cores Implement

### ISSUE THREAD

**Issue by ashraful1980** [iceland2k14/bsgs#15]
Dear Sir,
I would like to request you please implement the Thread or Cores Implement at "bsgs_hybrid_gmp.py" it will be found more speed. Also multiple public key file need to detected at a time; it will be helpful for me.

Regards,
Md. Ashraful Alam

**Comment by iceland2k14** [comment]
Thanks.
Multi cpu code will be added later when overall performance is increased. 
Just Now updated the bloom handling part using dll, with x3 performance gain.

**Comment by ashraful1980** [comment]
Dear Sir,
Have a nice day and hope you are doing well.

Thank you very much it is much powerful for single public key. But i also request you please added "-pfile Pub50.txt" including the bsgs_dll_gmp.py file which as multiple public key scan and detect  once a time.

Regards,
Md. Ashraful Alam

**Comment by iceland2k14** [comment]
Hybrid mode will be updated later after some more tests and changes.

**Comment by ashraful1980** [comment]
Thanks for quick response; i am waiting for further update...
