### ISSUE TITLE
Where is x3 speed acceleration? :))

### ISSUE THREAD

**Issue by mrantonion** [iceland2k14/bsgs#16]
There are so little arguments to use. Thus i can't see the acceleration as written earlier. :)

With keyhunt i used 15  threads and got a speed of 1x10^15 per 1 (one!!!) thread. (1000 trillion per thread).
Running this code i see just 500 trillions per 15 threads... Very slow.
![bsgs_001](https://user-images.githubusercontent.com/78864485/115000109-1c84e600-9eab-11eb-93f8-8bfa82e1cdfa.PNG)

May be i need to create a bPfile with much more elements in it?
I created it with 50M points.

Keyhunt example:
![keyhunt_004](https://user-images.githubusercontent.com/78864485/115009059-88b81780-9eb4-11eb-8e77-046c546147f2.PNG)

**Comment by iceland2k14** [comment]
1. The elements in bPfile will affects the speed as it will add more items in bloom to check in each loop, so more speed. With 6 billion items in bPfile added to bloom you should get x120 times faster compared to the image above.
2. Performance improvement was related to earlier python only code which i moved to folder. Not related to keyhunt. Keyhunt is faster.
3. This code is still 1 thread only. Multicpu will be added later after more changes.
4. So little arguments, i don't know about it??

**Comment by mrantonion** [comment]
> 1. The elements in bPfile will affects the speed as it will add more items in bloom to check in each loop, so more speed. With 6 billion items in bPfile added to bloom you should get x120 times faster compared to 50M items.
> 2. Performance improvement was related to earlier python only code which i moved to folder. Not related to keyhunt. Keyhunt is faster.
> 3. This code is still 1 thread only. Multicpu will be added later after more changes.
> 4. So little arguments, i don't know about it??

1. Got it.
2. I run it on python 3.8.
3. Now i understand. Thus i saw a 1-thread speed.
4. I meant smth like quantity of cpu threads, or predefined range, or continuously/random search switch.

Anyway thank you very much for software. Waiting for multicpu version! :)
