### ISSUE TITLE
20000000 or???

### ISSUE THREAD

**Issue by elvis13-prog** [iceland2k14/bsgs#19]
python create_bPfile.py 20000000 bPfile.bin
my computer has 32 gigabyte  RAM, how many million should I put in a file?

**Comment by elvis13-prog** [comment]
for 120 pazzle

**Comment by iceland2k14** [comment]
- I think it's better to use the mcpu script using 4 cpu (or more) when creating bPfile "create_bPfile_mcpu.py"
- 1 Biilion items makes 5GB bloom file to fill in the RAM. bPfile will be bigger, but does not matter after the bloom file is ready.

So perhaps you can try to use 4500000000 items. Use the latest file "bPfile_2_bloom_dll.py" when your bPfile is ready.
i am fixing a RAM bug now in it.

**Comment by elvis13-prog** [comment]
Yes thank you! Let me know as soon as the "bug" is fixed.

**Comment by elvis13-prog** [comment]
> Yes thank you! Let me know as soon as the "bug" is fixed.
What an argument  "-n 50000000000000"  ?

**Comment by iceland2k14** [comment]
Bug is fixed. Argument -n 50000000000000 means you search 50 Trillion keys in 1 go, and then proceed according to sequential or random mode selected.

**Comment by elvis13-prog** [comment]
When you run "python bPfile_2_bloom_dll.py bpfile.bin bloomfile.bin" you get an error. FileNotFoundError: Could not find module 'bloom.dll' (or one of its dependencies). Try using the full path with constructor syntax.
Help!
