### ISSUE TITLE
Use bsgs_v4_gmp.py for multiple public key search

### ISSUE THREAD

**Issue by ashraful1980** [iceland2k14/bsgs#2]
Dear Sir,
Have a nice day and hope you are well.

Thanks for your nice private key Search program; it is work as per the requirements. Could you please generate multiple public key search option at bsgs_v4_gmp.py. I have test with at bsgs_algo_modified_multi.py; it is slower to bsgs_v4_gmp.py as below command.
python3 bsgs_algo_modified_multi.py -n 180000000000000 -keyspace 800000000000000000000000000000:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF -rand

Kind Regards,
Md. Ashraful Alam

**Comment by iceland2k14** [comment]
Thanks for trying.
Yes this is the plan. I will add this and will delete old versions script.
