### ISSUE TITLE
hi there,

### ISSUE THREAD

**Issue by dextronomous** [iceland2k14/bsgs#21]
Got one question, am doing a 45000 chunks big 200000000000, is this feasible, the threads i enabled with .py 200000000000 bPfile.bin 24 but it is using 1 cpu to create the files. it has got 24 pythons opened up. but one in use. other 0%, thanks for looking.
and was wondering, this file becomes very big.  so 1.000.000.000 is 320gb. 10k chunks, so guess around 2 tb? is that smart to use, better? thanks for the help.

**Comment by iceland2k14** [comment]
There are some inconsistency in your numbers, but let me explain in simple way.

**You need to first see how much RAM you are going to use**. That's how you **decide bPfile elements**.
Let's say **i have a 32GB RAM** in my system of which approx **25GB is free**. rest is used by OS and other programs.
Then **my bloomfile** can **not** be more than **25GB**. 

By using, **1 billion elements i get 5GB bloom**. So it means, i should approx make 4.5 billion (4,500,000,000) elements to run in 32GB system.

bPfile each 1 element is 32 byte. **So 4.5 billion items will make 144 GB bPfile** which will be converted into 25GB bloomfile and that will be used in your RAM. That is the way to proceed.

**Comment by dextronomous** [comment]
hi thanks so much for explaining, i am having another issue, can it use more then 1 cpu when creating the bpfile bpfile_2_blooom_dll.py is not using more cpus then one whatever i tried, and that one has only got 10% usage. but now if having 320GB bpfile, and bloom is now 46GB then it means with 192 ram it should be good i guess, thank you.

**Comment by iceland2k14** [comment]
If you are in windows, the development branch has a script which creates bloom in batch. But still 1 cpu. As filling bloom in different threads has a huge overhead of modification all the time.
This is faster than current main branch script. In case you are still doing big files.
