### ISSUE TITLE
error when using pubsub.py development

### ISSUE THREAD

**Issue by unclevito2017** [iceland2k14/bsgs#25]
python --version Python 2.7.18
 python pubsub.py 02CEB6CBBCDBDF5EF7150682150F4CE2C6F4807B349827DCDBDD1F2EFA885A2630 100000 120 keysub120.bin
  File "pubsub.py", line 97
    if m%10000==0: print('[+] Finished Total SubKeys # ', m, end= '\r')
                                                             ^
SyntaxError: invalid syntax

python3 --version Python 3.8.5
python3 pubsub.py 02CEB6CBBCDBDF5EF7150682150F4CE2C6F4807B349827DCDBDD1F2EFA885A2630 100000 120 keysub120.bin
Traceback (most recent call last):
  File "pubsub.py", line 40, in <module>
    ice = ctypes.CDLL('ice_secp256k1.dll')
  File "/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: ice_secp256k1.dll: cannot open shared object file: No such file or directory

python3 pubsub.py 02CEB6CBBCDBDF5EF7150682150F4CE2C6F4807B349827DCDBDD1F2EFA885A2630 100000 120 keysub120.txt
Traceback (most recent call last):
  File "pubsub.py", line 40, in <module>
    ice = ctypes.CDLL('ice_secp256k1.dll')
  File "/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: ice_secp256k1.dll: cannot open shared object file: No such file or directory

Using Ubuntu 20.04 WSL under Win 10
bitcoin keysubtracter from albertobsd works on WSL is the output compatible

**Comment by iceland2k14** [comment]
Development Branch is still Windows. Linux is not not yet finished.
