### ISSUE TITLE
GPU implementation

### ISSUE THREAD

**Issue by ashraful1980** [iceland2k14/bsgs#26]
For GPU implementation:

https://www.geeksforgeeks.org/running-python-script-on-gpu/
https://thedatafrog.com/en/articles/boost-python-gpu/
https://numba.pydata.org/

Could you try this please...

**Comment by ashraful1980** [comment]
Dear Sir,
I could not find bsgs / v5_secp256k1_bloom_dll; could you please give me shared link. 

![bsgs](https://user-images.githubusercontent.com/52574658/123605511-bb1fb280-d81d-11eb-99bd-f54f555bc53b.jpg)

**Comment by iceland2k14** [comment]
Development Branch [https://github.com/iceland2k14/bsgs/tree/development](https://github.com/iceland2k14/bsgs/tree/development)

**Comment by ashraful1980** [comment]
Dear Sir,
Thanks for sharing bsgs/tree/development software; could please try For GPU implementation:

https://www.geeksforgeeks.org/running-python-script-on-gpu/
https://thedatafrog.com/en/articles/boost-python-gpu/
https://numba.pydata.org/

**Comment by ashraful1980** [comment]
Dear Sir,
I have try to create bpfile.bin; several time. Although it is not created here. Please see the bellow attached....

![image](https://user-images.githubusercontent.com/52574658/123753151-588cec00-d8db-11eb-973f-d20fb3214065.png)

**Comment by dextronomous** [comment]
the bpfile 400000000 is very big, even a smaller one toook me a week, the bloom from that one took also a week almost to create. 
btw. please add gpu, bsgs, thanks.

**Comment by ashraful1980** [comment]
Thanks for your valuable response. I will command 10 chunks instead of 40 & lets try it...

**Comment by iceland2k14** [comment]
I don't really understand your issue. 400 000 000 is nothing.
For me 2 000 000 000 created the bpFile of 62GB size in 2 hours using 4 cpu. 

Maybe if your pc has very low RAM (4GB). Then you can reduce the chunk in the code from 10 000 000 to 1 000 000. It will make shorter chunks but will be slower.

**Comment by dextronomous** [comment]
aha i used the dev env. with the main env. bloom.py mixed up, sorry bout that, did another try was 200 000 000 000, sorry bout that, this one took 2 days, 625gig and 105gig, thanks great progs you got thanks a lot man.

**Comment by ashraful1980** [comment]
Dear Sir,
Have a nice day we know that it is possible to adding GPU implementation. Attached bellow code & some link for your kind reference.  Your script is amazing speed; once adding GPU Cuda Core plus CPU all thread; it will be more specific speed. So please adding additinal GPU core....

https://www.geeksforgeeks.org/running-python-script-on-gpu/
https://thedatafrog.com/en/articles/boost-python-gpu/
https://numba.pydata.org/

![image](https://user-images.githubusercontent.com/52574658/131964340-84216d89-c998-466d-b52f-86c8ab9c7b68.png)
[python_GPU_SHA256.zip](https://github.com/iceland2k14/bsgs/files/7103899/python_GPU_SHA256.zip)
