### ISSUE TITLE
hi there, Bloom collision... 

### ISSUE THREAD

**Issue by dextronomous** [iceland2k14/bsgs#32]
how are you sir? question is a bloom collision... Checking inside the bPfile Now... how long should that take with 1 file 625gb another 105 and it is taking long time now. is this ok? thanks

**Comment by iceland2k14** [comment]
Ok. I fixed than in the latest commit @https://github.com/iceland2k14/bsgs/commit/a372cead40cc7b0bacd7151a63733fc099f41b61

Now collison checking is quick.

**Comment by dextronomous** [comment]
oof haha thanks so much for your great coding Senor, again we will speak.
