### ISSUE TITLE
ValueError: non-hexadecimal number found in fromhex() arg at position 131

### ISSUE THREAD

**Issue by kpot87** [iceland2k14/bsgs#41]
D:\Downloads\bsgs-main(1)\bsgs-main\v5_secp256k1_bloom_dll>python bsgs_hybrid_dll_secp256k1.py -pfile test_pubkeys.txt -b bPfile.bin -bl bloomfile.bin -n 50000000000000000  -rand1

[+] Starting Program : BSGS mode with hybrid algo using bloom dll and secp256k1 dll     Version [ 13072021 ]
Traceback (most recent call last):
  File "bsgs_hybrid_dll_secp256k1.py", line 311, in <module>
    Qlist = [ bytes(bytearray(pub2upub(line))) for line in read_pubkey_file() ]
  File "bsgs_hybrid_dll_secp256k1.py", line 311, in <listcomp>
    Qlist = [ bytes(bytearray(pub2upub(line))) for line in read_pubkey_file() ]
  File "bsgs_hybrid_dll_secp256k1.py", line 278, in pub2upub
    return bytes.fromhex('04'+ hex(x)[2:].zfill(64) + hex(y)[2:].zfill(64))
ValueError: non-hexadecimal number found in fromhex() arg at position 131

List of PunKeys

04180bfa57bff462c7641fa0b91efe29344a77086b073cd9c5f769cb2393acc151a4e7377eaabacc39f5b2bd2cd4bcb5ed1855939619e491c79c0bb5793d4edbf3ac
04bb31566291ceb63ed600b0c29d6825d7924e73c265abac43fa088ad3e1a477c6fd15373fc40229cc895732d4175f6db615e4a2b6e9411e92974b6923d7985518ac
04ce29c26fb59eadf6b9b38a3e7f52646877bcdcd7b5f290a47a7a61668bda2c82c8f13f66e8665cfe7594d7da51f431df4df2f60df08ecfd53d2f2d076b4bc24eac
04655798e5ce83da2f24955e16396846528d919c223c9c2945b211b722d55a85ccb8930066eaf34c501ac37c4d41c8e579ccc00f54d5a5f1b3c27de525ece5a5d5ac
046312c744cb65614769150309590257c89cf5d2ee4f048e5a944fa50c768d205ee6083314a55d8b3f9caff539758c13a8f73be4aac6a6e8c5a917dc670e042f11ac
046154d4ed678ddf5fbb9e09ef7d1cf3a8053f5a09fc89303d150d4e715bc691b240c93729cd412d707c48f7bafe41db684c2f9a39aa5995786827e9ed4d185e36ac
0427df882a156b4c29a4d05eec8d0c4b53f976f7e0ee2639dc8cbb6327451b8cf0957abb3418696243f392e73b586ea4b074e5bdc856a234c9e174615e3bbcea24ac
04a449ee292e46745b6e8e350a04777ee938f151af438a6b80c2fb86a65e71e6a677897ef1f8e997dcddc024d92639620e09021710ae3076836c90f3fa2fcdedd3ac
04462b00d67b254e4b10de6fe0b277b6a34f2438758fc5fc2c18c5b53e9352322b94d2be6ca5a2557ebf55905f7dc6cca699162b0faf919754b5ca369d31d0bb31ac
0492ade9a7a1fde25016c02d223e2f1c501d2af11b492e0a3f0cd617a01798c5f5eabd9d5957a7b2d66d1b42f688a6fd5d2bc60ad0d7a00f6006fc4838fb4c248aac
04c9eb99d7bbbd9acfab695c8aa8b931beb43292f2fecdc19d7e687b524d2e2c8a9d167f9be930634adae005424b441a9de8e8c15d8b2462661eb78418a8aba662ac
04e049e5c6fb83743c8ef0a640cc82ea14191026643e3e2a1c84edf168bb9690f3c201d04a30c8609aa9406c1eb565e1b9fa218317da5177060de158f25ccc879dac
04da82f7361830281e40cf9a8fbc5fea33f35d52ef06b7a72e4b12665374f843839f4a7ad2021e07377c58eb14cc1d01d2017a38281910b6935182cff99930dd8bac
04a4a43c49a491bcad58a1578ddeed00ee13ac58c33a4d50fdb0b06d2ca97b6791097e127f9a4fe2d8f952b2420ef82c669c84d3e65d4fce257d707ec214562c29ac
0455f09e54cc544e9f61d0394db1bec90c30ea89c88c554196ebb68e9c8e02c5ea7f3291521dddb44abee835ed376152f04039634ae7af2b5ef2587776348d0b34ac
048644947f13359243d46be6436fb04bc20f92c1ed34b9548b31838bdb5ef721da70c360f2a8886e47addf7b3f87142b5245d95c9bbd6e36f43055998174db8417ac

what it can be? thank you

**Comment by iceland2k14** [comment]
Your Pubkeys are 132 hex which means 66 bytes. It is not correct. Upub must be 65 bytes only.
I think your parsing of pubkeys have some issue. Maybe the last "ac" is not correct or maybe some more things also in it. Find the correct pubkey

**Comment by kpot87** [comment]
Ok thank you yes the “ac” is the problem.
