### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by sssergy** [iceland2k14/bsgs#44]
![image](https://user-images.githubusercontent.com/26333870/139919654-8774acd6-cda0-4051-a61e-8ba78d2b9ed5.png)

The previous version worked without errors.

**Comment by iceland2k14** [comment]
@sssergy i have not changed anything in the search. the v6 was only to create the bloom files quickly. Also the secp256 dll files are changing all the time with more and more functions added and removed. So they are not to be mixed. Otherwise i don't know why segmentation fault.

**Comment by iceland2k14** [comment]
Updated the script
