### ISSUE TITLE
cant find private key

### ISSUE THREAD

**Issue by ramin1234** [iceland2k14/bsgs#48]
hi
Public key of F0001000000000001 is 
04F50CF235C38DAF3106727063CC3EE9EFC631A08F99F77C6A5B8AAA03D9007DBB439209AE5FB59096FCC5874ED940906D2580928CF74028C1C3E1F5AF496D1414
i added in 1.txt
then run this code
python bsgs_hybrid_dll_secp256k1.py -pfile 1.txt -b bPfile.bin -bl bloomfile.bin -n 500000000000000 -keyspace F0001000000000001:F0001000500000001

result : bsgs found private key F0001000000000001

but when i add the Public key of F0001000000000002 to 1.txt .
It cant find it 

why?

**Comment by ramin1234** [comment]
@iceland2k14 
04CB2DA061F7C5A8178651A0BBA315B7AF83CBA3EB4EC7553F81A1F4C58C7BB3613C6758765787DC03C7D079169A780A9421C902DB098B1EE7BB527954BC50C318
cant find this .

**Comment by ramin1234** [comment]
@@iceland2k14

**Comment by iceland2k14** [comment]
Please see example in v6_dll_bsgs
