### ISSUE TITLE
suggestion for faster search in multi public key

### ISSUE THREAD

**Issue by ramin1234** [iceland2k14/bsgs#49]
for Q in Qlist:
        found = bsgs_keys(Q, k1, k2)

You call this code for each public key but it may have been generated in the previous Q

**Comment by ramin1234** [comment]
@iceland2k14

**Comment by iceland2k14** [comment]
Line 374

**Comment by ramin1234** [comment]
in this file bsgs_hybrid_dll_secp256k1.py??

**Comment by iceland2k14** [comment]
in v6
