### ISSUE TITLE
autosave found keys

### ISSUE THREAD

**Issue by dextronomous** [iceland2k14/bsgs#51]
hi there sir,
thanks for the great works, really again thanks so much, can this be done, thank you.

**Comment by iceland2k14** [comment]
Yes. This has been pending too long. Let me do it immediately.

**Comment by iceland2k14** [comment]
Found Key is saved in KEYFOUNDKEYFOUND.txt

**Comment by dextronomous** [comment]
oh wow man really you the greatest works thanks for this fix
