### ISSUE TITLE
Support for multiple keys

### ISSUE THREAD

**Issue by Mezantrop74** [iceland2k14/bsgs#8]
Hello.
Can you add support for checking multiple public keys to your script bsgs_v4_gmp.py ?
Assuming the key file is large, approximately 5 million public keys.

**Comment by iceland2k14** [comment]
Yes this is in progress with hybrid bsgs. Will be uploaded here, sometime in future. Thanks

**Comment by Mezantrop74** [comment]
Hello. I have a few questions, but they are not relevant to this topic.
Could you contact me?
My mail is listed in the profile.
Thank you

**Comment by Mezantrop74** [comment]
Bloom filter search gives strange results.
Shows that the key was found, but does not show the key, but writes that you need to re-run the script to search in the range that the script showed.
When the script runs in this range, it again shows the same message that needs to be run in the range it specified.
When you run other similar programs in this range, which shows the script does not find anything.

**Comment by vanrzuf** [comment]
That's false positive from bloom filter. Maybe better idea to handle false positive's is to store them for later check, rather than terminating script.

**Comment by Mezantrop74** [comment]
> That's false positive from bloom filter. Maybe better idea to handle false positive's is to store them for later check, rather than terminating script.

Interesting fact.
If I use a regular public key instead of a compressed one, this error does not occur.

**Comment by iceland2k14** [comment]
Yes i saw many False Positive. Updated the version. Also the bPfile.bin is required now, but only a very small portion of it is read. So no imprint in memory. Hope it resolves the issue.
