### ISSUE TITLE
false positive with bloom filter?

### ISSUE THREAD

**Issue by dolaor** [iceland2k14/bsgs#9]
Hi,

I think that the last version of your code which includes the bloom filter can return false positive private key since bloom filter is a probabilistic data structure. So I am not sure if it is relevant to include it in the code. What do you think about it?

**Comment by iceland2k14** [comment]
Yes Correct. Althought i used probability of False +ve of 10^-9. 
But still it was giving some collisions. I fixed it now, by updating the version. Also the bPfile.bin is required now, but only a very small portion of it is read. So no imprint in memory. Hope it fixed the issue.
